### ISSUE TITLE
Update release team membership

### ISSUE THREAD

**Issue by christianrauch** [ros2-gbp/ros2-gbp-github-org#108]
# Updates to apriltag membership.

I would like to release the ROS2 packages [apriltag_msgs](https://github.com/christianrauch/apriltag_msgs) and [apriltag_ros](https://github.com/christianrauch/apriltag_ros) and are therefore requesting to join the `apriltag` release team.

## New team members

* @christianrauch
* @christian-rauch

**Comment by nuclearsandwich** [comment]
Just confirming for my own edification, these accounts are both yours but one is work associated correct?

**Comment by nuclearsandwich** [comment]
@christianrauch since the current apriltag release team is comprised of maintainers of the upstream [apriltag](https://github.com/AprilRobotics/apriltag) project and adding you to that team would give you permission to make ROS 2 releases of that repository (and likewise grant them permissions to make releases of apriltag_msgs and apriltag_ros we would need to get a :+1: from either @wxmerkt or @mkrogius to proceed.

If you'd prefer one thing I can do without any further review I can create a new, separate release team, `apriltag_ros`, probably and add both `apriltag_ros-release` and `apriltag_msgs-release` to it with yourself as the sole member. Let me know if you prefer one over the other and we'll proceed.

**Comment by wxmerkt** [comment]
Happy for Christian to be added.

@christianrauch Regarding releasing apriltag_msgs/apriltag_ros, we should decide (e.g. as raised in https://github.com/AprilRobotics/apriltag_ros/issues/76 and https://github.com/AprilRobotics/apriltag_ros/issues/132) whether to go ahead with @wep21's port of the ROS1 version or @christianrauch's https://github.com/christianrauch/apriltag_ros which was in earlier ROS2 releases. I am not actively using either on ROS2 so cannot weigh in - in either case we should document it and ideally address divergence in features/messages. Perhaps best if you can coordinate with @wep21 and the users who've expressed usage of either in the comments/issues. Thank you :-).

**Comment by christianrauch** [comment]
> Just confirming for my own edification, these accounts are both yours but one is work associated correct?

Yes. I use @christianrauch for "private work" and @christian-rauch for "professional work".

**Comment by nuclearsandwich** [comment]
> Regarding releasing apriltag_msgs/apriltag_ros, we should decide (e.g. as raised in [AprilRobotics/apriltag_ros#76](https://github.com/AprilRobotics/apriltag_ros/issues/76) and [AprilRobotics/apriltag_ros#132](https://github.com/AprilRobotics/apriltag_ros/issues/132)) whether to go ahead with wep21's port of the ROS1 version or christianrauch's https://github.com/christianrauch/apriltag_ros which was in earlier ROS2 releases.

I'm going to close this issue temporarily pending the outcome of those discussions.

**Comment by christianrauch** [comment]
> I'm going to close this issue temporarily pending the outcome of those discussions.

Regardless of which repo gets released,  can you make me a release team member anyway? In any case, it would be useful to be able to release the library or (ROS1) node packages.

**Comment by nuclearsandwich** [comment]
> Regardless of which repo gets released, can you make me a release team member anyway? In any case, it would be useful to be able to release the library or (ROS1) node packages.

Done and deployed in #129.
