### ISSUE TITLE
Add release team `teamspatzenhirn`

### ISSUE THREAD

**Issue by ottojo** [ros2-gbp/ros2-gbp-github-org#112]
* Name of the new release team: teamspatzenhirn
* Release repositories to add:
  * [rviz_2d_overlay_plugins](https://github.com/teamspatzenhirn/rviz_2d_overlay_plugins)

* Team members
  * @ottojo https://github.com/teamspatzenhirn/rviz_2d_overlay_plugins/blob/main/rviz_2d_overlay_plugins/package.xml#L10
  * @authaldo https://github.com/teamspatzenhirn/rviz_2d_overlay_plugins/blob/main/rviz_2d_overlay_plugins/package.xml#L11

**Comment by nuclearsandwich** [comment]
Hi @ottojo thanks for completing the issue template, we're in the process of updating our review procedures so there's an additional request before I add the release repository requested.

Can you please open a pull request on [ros/rosdistro](https://github.com/ros/rosdistro/) adding a source entry for your repository to [`rolling`](https://github.com/ros/rosdistro/blob/master/rolling/distribution.yaml). There is some information about the requirements here: https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#guidelines-for-package-naming

You do not need to perform a complete binary release (since doing so would require a configured release repository) but it's important that your package undergo the license and naming review before a release repository is created.

Thanks and let me know if you have any questions.

**Comment by ottojo** [comment]
Ping @nuclearsandwich , the PR in ros/rosdistro https://github.com/ros/rosdistro/pull/34612 is merged

**Comment by nuclearsandwich** [comment]
Thanks for the ping. This team has been created!
