### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by progtologist** [ros2-gbp/ros2-gbp-github-org#121]
* Name of the new release team: progtologist
* Release repositories to add:
  * [ffmpeg_image_transport](https://github.com/progtologist/ffmpeg_image_transport)
   - [x] There is an existing release repository which should be imported: [ffmpeg_image_transport-release](https://github.com/progtologist/ffmpeg_image_transport-release)

* Team members
  * [@progtologist](https://github.com/progtologist/ffmpeg_image_transport/blob/main/package.xml#L7)

**Comment by nuclearsandwich** [comment]
Thanks for following the template @progtologist.

We're in the process of updating our review procedures so there's an additional request before I add the release repository requested.

Can you please open a pull request on [ros/rosdistro](https://github.com/ros/rosdistro/) adding a source entry for your repository to [rolling](https://github.com/ros/rosdistro/blob/master/rolling/distribution.yaml). There is some information about the requirements here: https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#guidelines-for-package-naming

You do not need to perform a complete binary release (since doing so would require a configured release repository) but it's important that your package undergo the license and naming review before a release repository is created.

Thanks and let me know if you have any questions.

**Comment by nuclearsandwich** [comment]
@progtologist I am going to close this issue for now but please re-open it when you have added a source entry as described above or let me know if you have any additional questions.
