### ISSUE TITLE
Add new release repositories

### ISSUE THREAD

**Issue by tylerjw** [ros2-gbp/ros2-gbp-github-org#163]
* Name of the release team: moveit

* Release repositories to add:
  * [pick_ik](https://github.com/pickNikRobotics/pick_ik)
    * [x] There is an existing release repository which should be imported: <https://github.com/pickNikRobotics/pick_ik-release>
  * [rsl](https://github.com/pickNikRobotics/rsl)
    * [x] There is an existing release repository which should be imported: <https://github.com/pickNikRobotics/rsl-release>
  * [generate_parameter_library](https://github.com/pickNikRobotics/generate_parameter_library)
    * [x] There is an existing release repository which should be imported: <https://github.com/picknikrobotics/generate_parameter_library-release>

**Comment by tfoote** [comment]
This looks good to me. Once we get back from the holiday vacations we should be able to import these.

**Comment by nuclearsandwich** [comment]
The release repositories have been imported to ros2-gbp and the team permissions access is deploying now.

I would recommend archiving the pickNikRobotics release repositories to prevent pushing to them unintentionally, they ideally should not be deleted outright in order to allow older versions of the rosdistro database to continue to function as expected.
