### ISSUE TITLE
Add release team: cascade_lifecycle

### ISSUE THREAD

**Issue by fmrico** [ros2-gbp/ros2-gbp-github-org#168]
* Name of the new release team: cascade_lifecycle
* Release repositories to add:
  * [cascade_lifecycle](https://github.com/fmrico/cascade_lifecycle.git)
    * [x] There is an existing release repository which should be imported: https://github.com/fmrico/cascade_lifecycle-release.git

* Team members
  * [fmrico](https://github.com/fmrico/cascade_lifecycle/blob/master/cascade_lifecycle_msgs/package.xml)

**Comment by nuclearsandwich** [comment]
Thanks for your patience as we ramp back into things after the end of year holidays!

The release repository above has been imported into ros2-gbp. I recommend archiving https://github.com/fmrico/cascade_lifecycle-release.git so that it remains available for anyone using an earlier ros/rosdistro index but cannot be pushed to by mistake.

**Comment by nuclearsandwich** [comment]
This change has been deployed!
