### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by jaiveersinghNV** [ros2-gbp/ros2-gbp-github-org#254]
* Name of the new release team: nvidia
* Release repositories to add:
  * [ros2_benchmark](https://github.com/NVIDIA-ISAAC-ROS/ros2_benchmark)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>

* Team members
  * [@jaiveersinghNV](https://github.com/NVIDIA-ISAAC-ROS/ros2_benchmark/blob/main/ros2_benchmark/package.xml#L31)
  * [@hemalshahNV](https://github.com/NVIDIA-ISAAC-ROS/ros2_benchmark/blob/main/ros2_benchmark/package.xml#L27)

**Comment by nuclearsandwich** [comment]
Hello @jaiveersinghNV, in order to prepare a release repository for this project, could you please open a PR on https://github.com/ros/rosdistro which adds a source entry for these packages to Rolling or Humble. A full binary release isn't expected, since this is a preferred prerequisite for one, but submitting the source entry will allow the packages to go through naming and licensing review before release.

When that PR is open, you can link it here and bump again when it merges.

**Comment by jaiveersinghNV** [comment]
Hi @nuclearsandwich ! I've just opened the PR for adding `ros2_benchmark` to the Humble `distribution.yaml` here:
https://github.com/ros/rosdistro/pull/37353

**Comment by nuclearsandwich** [comment]
@jaiveersinghNV since the rosdistro PR that this issue is tracking has been closed, I'm going to close this one as well. Please do re-open it, or open a new issue referencing this one, when the package has been re-submitted.
