### ISSUE TITLE
Add new release repositories

### ISSUE THREAD

**Issue by marip8** [ros2-gbp/ros2-gbp-github-org#258]
* Name of the release team: `ros-industrial`

* Release repositories to add:
  
  * [reach](https://github.com/ros-industrial/reach)
  * [reach_ros2](https://github.com/ros-industrial/reach_ros2)

**Comment by nuclearsandwich** [comment]
Hi @marip8, since these appear to be packages that are new to ROS, can you please open a PR on https://github.com/ros/rosdistro which adds a `source` entry for them in an active ROS 2 distribution. This will ensure that the packages go through new package review before release repositories are created.

Thanks!

**Comment by marip8** [comment]
I just opened the PR [here](https://github.com/ros/rosdistro/pull/37635)

**Comment by marip8** [comment]
@nuclearsandwich rosdistro links for:
- [humble](https://github.com/ros/rosdistro/blob/f8caa53828ed3da50de2900a3a61f08f260639af/humble/distribution.yaml#L4924-L4933)
- [rolling](https://github.com/ros/rosdistro/blob/f8caa53828ed3da50de2900a3a61f08f260639af/rolling/distribution.yaml#L4171-L4180)

**Comment by nuclearsandwich** [comment]
This change has been deployed!
