### ISSUE TITLE
Update release team membership

### ISSUE THREAD

**Issue by deyouslamtec** [ros2-gbp/ros2-gbp-github-org#261]
# Updates to  membership.

## New team members

* [@deyouslamtec](https://github.com/Slamtec/rplidar_ros/blob/ros2/package.xml#L10)
* [@WubinXia](https://github.com/Slamtec/rplidar_ros/blob/ros2/package.xml#L11)

**Comment by nuclearsandwich** [comment]
@deyouslamtec can you please link to the package.xml maintainer entries in the source packages for these users in order to complete the [issue template](https://github.com/ros2-gbp/ros2-gbp-github-org/blob/latest/.github/ISSUE_TEMPLATE/update_release_team_membership.md).

Linking to the maintainer entry helps us confirm that this request is legitimately coming from the maintainer team of the source package.

**Comment by deyouslamtec** [comment]
@nuclearsandwich Hi，i have linked these users to maintainer entries in package.xml

**Comment by nuclearsandwich** [comment]
Thanks! implemented in #272 which will deploy shortly.

**Comment by nuclearsandwich** [comment]
This change has been deployed!
