### ISSUE TITLE
Bloom issue on tuw-robotics

### ISSUE THREAD

**Issue by maxbader** [ros2-gbp/ros2-gbp-github-org#266]
@nuclearsandwich I am looking for help for my group tuw-robotics and the package tuw_geometry related to https://github.com/ros/rosdistro/pull/37245

**Comment by nuclearsandwich** [comment]
Thanks for starting the issue! I'm going to include a bit of background that you may already be aware of, I'm doing it mostly to show what I know in case _I_ am the one missing background here.

In order to support the migration tools which allow us to update the platform values for Rolling and create new distributions from Rolling as a base rather than from scratch, we've centralized the ROS 2 release repositories in the ros2-gbp organization on GitHub to ensure that our automation always has access.

We're still at the encouragement rather than enforcement stage of getting everyone to use the ros2-gbp repositories consistently but we're moving in the enforcement direction as documentation and tooling help support the new workflows. Whenever the migration tool is run, if the current release repository _is not_ in ros2-gbp, it will create one there (or use one previously created) and use that for the automated release. When a repository outside ros2-gbp is used for subsequent releases, I try to manually merge the contents of the external release repository into the ros2-gbp one so it has all of the branch and tag history from the external release repository. For complex version histories, this can be a bit challenging and due to some details of bloom's internals, it can often result in scary warnings about force pushing for the `upstream` branch or `upstream/*` tags. As long as bloom is used for releases, and the upstream project adheres to immutable tags, the discrepancies between these tags are limited to commit metadata and not repository contents.

My goal is to "true up" the release repository in ros2-gbp and ensure that you have access to it so that the ros2-gbp repository can be used for releases going forward, I can also help troubleshoot why https://github.com/ros/rosdistro/pull/37245 is not passing checks once we get things taken care of. There is no technical reason I can't check that before we move the release repository, it's just a good time to take care of that as well.


---

There appear to be mutual discrepancies between the external release repository and the one in ros2-gbp.

I have pushed the tags from the releases created on the tuw-robotics repository to the ros2-gbp repository and merged the contents of the bloom configuration branch (`master`) so that the ros2-gbp repository should now be usable for subsequent releases.

According to the current version of [tuw_robotics.tf](https://github.com/ros2-gbp/ros2-gbp-github-org/blob/b85bc6dc3a1230b926401fcc8673780723d197b6/tuw_robotics.tf) in this repository you should already have access to the ros2-gbp repository for tuw_geometry-release.

I use 
```
bloom-release -r rolling tuw_geometry --override-release-repository-url https://github.com/ros2-gbp/tuw_geometry-release.git
```

I started a debug release (which I would not actually push) as a diagnostic to try and determine what the release issues might be and I am flummoxed

```
New ROS Distro index url: 'https://raw.githubusercontent.com/ros/rosdistro/1813cdde6bdb0b0abf9ba66d55ede1dd58080015/index-v4.yaml'
Generating source debs for the packages: ['tuw_geometry']
Debian Incremental Version: 3
Debian Distributions: ['focal']
Releasing for rosdistro: foxy

Pre-verifying Debian dependency keys...
Running 'rosdep update'...
All keys are OK

Placing debian template files into 'debian/foxy/tuw_geometry' branch.
==> Placing templates files in the 'debian' folder.

####
#### Generating 'focal' debian for package 'tuw_geometry' at version '0.0.9-3'
####
Generating debian for focal...
```

Somehow the `rolling` track in bloom is trying to build for foxy rather than rolling.

**Comment by nuclearsandwich** [comment]
In the end it was a misconfiguration. I've opened https://github.com/ros2-gbp/tuw_geometry-release/pull/1 to correct it. When that PR merges, it should make releasing tuw_geometry from the ros2-gbp repository possible and hopefully successful.

**Comment by nuclearsandwich** [comment]
@maxbader I see that the fix I proposed above has merged I haven't seen if you were able to get a new release out. Would you please close this one if you were able to resolve the issues with a new release?

**Comment by maxbader** [comment]
Thanks it works now

**Comment by maxbader** [comment]
Sorry for reopening the issue but the[ build #22 failed ](https://build.ros2.org/job/Fdev__tuw_geometry__ubuntu_focal_amd64/changes) 
Similar thing happed to [tuw_msgs](https://build.ros2.org/job/Fdev__tuw_msgs__ubuntu_focal_amd64/changes)
```
Traceback (most recent call last):
  File "/tmp/ros_buildfarm/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 287, in resolve_names
    resolved_names = resolve_for_os(
  File "/usr/lib/python3/dist-packages/rosdep2/catkin_support.py", line 87, in resolve_for_os
    d = view.lookup(rosdep_key)
  File "/usr/lib/python3/dist-packages/rosdep2/lookup.py", line 206, in lookup
    return self.rosdep_defs[rosdep_name]
KeyError: 'ros_workspace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 21, in <module>
    run_module('ros_buildfarm.scripts.devel.create_devel_task_generator', run_name='__main__')
  File "/usr/lib/python3.8/runpy.py", line 210, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ros_buildfarm/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 304, in <module>
    sys.exit(main())
  File "/tmp/ros_buildfarm/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 126, in main
    debian_pkg_names += resolve_names(['ros_workspace'], **context)
  File "/tmp/ros_buildfarm/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 290, in resolve_names
    raise RuntimeError(
RuntimeError: Could not resolve the rosdep key 'ros_workspace'
Build step 'Execute shell' marked build as failure
[CMakeGNU C Compiler (gcc)Clang-Tidy] Skipping execution of recorder since overall result is 'FAILURE'
INFO: Processing CTest-Version 3.x (default)
INFO: [CTest-Version 3.x (default)] - No test report file(s) were found with the pattern 'ws/test_results/*/Testing/*/Test.xml' relative to '<https://build.ros2.org/job/Fdev__tuw_geometry__ubuntu_focal_amd64/ws/'> for the testing framework 'CTest-Version 3.x (default)'.
Did you enter a pattern relative to (and within) the workspace directory?
Did you generate the result report(s) for 'CTest-Version 3.x (default)'?"
INFO: Processing GoogleTest-1.8
INFO: [GoogleTest-1.8] - No test report file(s) were found with the pattern 'ws/test_results/**/*.gtest.xml' relative to '[<https://build.ros2.org/job/Fdev__tuw_geometry__ubuntu_focal_amd64/ws/'>](https://build.ros2.org/job/Fdev__tuw_geometry__ubuntu_focal_amd64/ws/') for the testing framework 'GoogleTest-1.8'.
Did you enter a pattern relative to (and within) the workspace directory?
Did you generate the result report(s) for 'GoogleTest-1.8'?"
INFO: Processing JUnit
INFO: [JUnit] - No test report file(s) were found with the pattern 'ws/test_results/*/pytest.xml' relative to '[<https://build.ros2.org/job/Fdev__tuw_geometry__ubuntu_focal_amd64/ws/'>](https://build.ros2.org/job/Fdev__tuw_geometry__ubuntu_focal_amd64/ws/') for the testing framework 'JUnit'.
Did you enter a pattern relative to (and within) the workspace directory?
Did you generate the result report(s) for 'JUnit'?"
INFO: Processing JUnit
INFO: [JUnit] - No test report file(s) were found with the pattern 'ws/test_results/**/*.xunit.xml' relative to '<https://build.ros2.org/job/Fdev__tuw_geometry__ubuntu_focal_amd64/ws/'> for the testing framework 'JUnit'.
Did you enter a pattern relative to (and within) the workspace directory?
Did you generate the result report(s) for 'JUnit'?"
WARNING: All test reports are empty.
INFO: Check 'Failed Tests' threshold.
INFO: Check 'Skipped Tests' threshold.
INFO: Setting the build status to FAILURE
```

**Comment by clalancette** [comment]
I wouldn't worry too much about those failed jobs; Foxy is now [EOL](https://discourse.ros.org/t/new-packages-for-foxy-fitzroy-2023-06-20/32039), so even if there is something to fix there we can't fix it anyway.

More important are https://build.ros2.org/job/Hdev__tuw_geometry__ubuntu_jammy_amd64/, https://build.ros2.org/job/Idev__tuw_geometry__ubuntu_jammy_amd64/, and https://build.ros2.org/job/Hdev__tuw_msgs__ubuntu_jammy_amd64/, all of which seem to be building properly.

**Comment by nuclearsandwich** [comment]
> Sorry for reopening the issue but the[ build #22 failed ](https://build.ros2.org/job/Fdev__tuw_geometry__ubuntu_focal_amd64/changes)
> Similar thing happed to [tuw_msgs](https://build.ros2.org/job/Fdev__tuw_msgs__ubuntu_focal_amd64/changes)

Devel jobs are unaffected by bloom releases and the failures were raised as [on ROS Answers](https://answers.ros.org/question/416825/build-fails-on-simple-msgs-packages-on-the-ros-2-buildfarm/?answer=416835#post-id-416835) which is the more appropriate venue to resolve them.
