### ISSUE TITLE
Update release team membership

### ISSUE THREAD

**Issue by MarqRazz** [ros2-gbp/ros2-gbp-github-org#280]
# Updates to `picknik_team` membership.

## New team members

[@moriarty](https://github.com/PickNikRobotics/ros2_robotiq_gripper/blob/58eda4b7f58052c427e79cec09bd4b302dcdd3cb/robotiq_description/package.xml#L8)
[@marqrazz](https://github.com/PickNikRobotics/ros2_robotiq_gripper/blob/58eda4b7f58052c427e79cec09bd4b302dcdd3cb/robotiq_description/package.xml#L9)

**Comment by nuclearsandwich** [comment]
In case I get lost today, the deployment of this PR was delayed because I hit the 5000 request rate limit after a few successive terraform plans. I should be updating within an hour confirming successful deployment but it's possible (given that it's Saturday) that time will get away from me while waiting.

**Comment by nuclearsandwich** [comment]
This change has been deployed!
