### ISSUE TITLE
Add new release repository picknik_controllers-release

### ISSUE THREAD

**Issue by moriarty** [ros2-gbp/ros2-gbp-github-org#283]
* Name of the release team: picknik
  * https://github.com/ros2-gbp/ros2-gbp-github-org/pull/281
  * Issue #280 

* Release repositories to add:
  
  * [picknik_controllers](https://github.com/PickNikRobotics/picknik_controllers)
    * ros/rosdistro source entry: https://github.com/ros/rosdistro/pull/37736
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>

The https://github.com/ros/rosdistro/pull/37736 hasn't been merged yet but I'm opening this issue early assuming there are no naming issues.

**Comment by nuclearsandwich** [comment]
> assuming there are no naming issues.

Opening the issue early is definitely welcome. I would still block release repository creation on approval of the REP-144 naming in particular since if they don't pass those review the release repository name is likely to change. In this case, I went ahead and did the source entry review as a prerequisite to approving this PR.

**Comment by nuclearsandwich** [comment]
In case I get lost today, the deployment of this PR was delayed because I hit the 5000 request rate limit after a few successive terraform plans. I should be updating within an hour confirming successful deployment but it's possible (given that it's Saturday) that time will get away from me while waiting.

**Comment by nuclearsandwich** [comment]
This change has been deployed!

**Comment by tylerjw** [comment]
picknik_controllers-release doesn't seem to exist as a repo, are we missing something?

**Comment by moriarty** [comment]
Hi @nuclearsandwich 

I still don't see a https://github.com/ros2-gbp/picknik_controllers-release

Does adding the line in #284 automatically get deployed or automatically create the repository eventually?
Or do we still need someone with permissions to manually create the release repository?

**Comment by moriarty** [comment]
Great, the repo was created today.

Thanks!
