### ISSUE TITLE
Update release team membership

### ISSUE THREAD

**Issue by nabetetsu** [ros2-gbp/ros2-gbp-github-org#329]
# Updates to `tier4` membership.

## New team members

@nabetetsu

**Comment by nuclearsandwich** [comment]
In order to update team members, I usually ask for some evidence that the new members are indeed maintainers of the packages which this team has access to. 

Most commonly, this is a link to a `<maintainer>` or `<author>` field in a package's package.xml file. For example: https://github.com/ros2/ros_workspace/blob/latest/package.xml#L14

Since this team corresponds to an organization on GitHub, public evidence of membership in the GitHub organization or a +1 from this team's current members: @wep21 would also be acceptable.

**Comment by wep21** [comment]
@nuclearsandwich It's no problem to add @nabetetsu only.

**Comment by nabetetsu** [comment]
Thank you for your comment, @nuclearsandwich @wep21 .

I changed New team members of this PR to @nabetetsu only.
Please reconfirm the PR.

**Comment by nabetetsu** [comment]
After consulting with @wep21, it was decided to create a new team `caret` instead of joining a tier4 team.
