### ISSUE TITLE
Humanoid Robot Intelligence Control System Module

### ISSUE THREAD

**Issue by RonaldsonBellande** [ros2-gbp/ros2-gbp-github-org#367]
Name of the release team: Ronaldson Bellande

Release repositories to add: https://github.com/Robotics-Sensors/humanoid_robot_intelligence_control_system_module

https://github.com/ros2-gbp/ros2-gbp-github-org/pull/366

**Comment by nuclearsandwich** [comment]
Hello @RonaldsonBellande in the future please follow the issue templates when requesting release repositories. As mentioned in https://github.com/ros2-gbp/ros2-gbp-github-org/issues/361#issuecomment-1817269459 there is information missing before these release repositories can be set up.

I would also prefer if you created a single issue for all repositories under a release team rather than an issue per repository. I am going to close the other open issues as duplicates of this one.

**Comment by RonaldsonBellande** [comment]
yea, each of the set of packages release are separated and have separate functionalities. As there are 6 release repositories.

**Comment by RonaldsonBellande** [comment]
https://github.com/ros/rosdistro/pull/39072

**Comment by nuclearsandwich** [comment]
Closing since the linked rosdistro PR has been closed. Feel free to re-open if the source package is added to a rosdistro.
