### ISSUE TITLE
Update release team membership

### ISSUE THREAD

**Issue by rostest** [ros2-gbp/ros2-gbp-github-org#472]
# Updates to sick_scan_xd membership.

## New team members

* [@michael.lehning@lehning.de](https://github.com/SICKAG/sick_scan_xd/blob/abd456030afbdbdc397e17450a99f935014923d2/package.xml#L8)

**Comment by nuclearsandwich** [comment]
@rostest we need the GitHub username that should be added, rather than the email address. The link to the corresponding maintainer tag in a package.xml is very much appreciated. Thanks!

I'm using the `needs-maintainer-link` label here even though I have that but am missing the GitHub username to add.

**Comment by rostest** [comment]
@nuclearsandwich Many thanks for your feedback! The github user name is michael1309 , @michael1309 .

**Comment by nuclearsandwich** [comment]
This change has been deployed!

**Comment by rostest** [comment]
@nuclearsandwich Many thanks!
