### ISSUE TITLE
LBR-Stack New ReleaseTeam

### ISSUE THREAD

**Issue by mhubii** [ros2-gbp/ros2-gbp-github-org#519]
Bear with me as this is our first release team. May I kindly ask you with support for adding a new release team? Thank you very much for the help in advance! :)

* Name of the new release team: lbr_stack
* Release repositories to add:
  - https://github.com/lbr-stack/lbr_fri_ros2_stack
  - https://github.com/lbr-stack/ros2_roboreg

* Team members
  * [@mhubii](https://github.com/lbr-stack/lbr_fri_ros2_stack/blob/653385328eb5cf11188a5d80b14fb4e16ef2ec62/lbr_fri_ros2_stack/package.xml#L7)
  * [@cmower](https://github.com/lbr-stack/lbr_fri_ros2_stack/blob/92769194d3266d7846392431fb0731596bf859c6/lbr_demos/lbr_demos_advanced_py/package.xml#L8)

**Comment by nuclearsandwich** [comment]
Hello @mhubii happy to help you out!

Before we can add the release repositories, we ask that you submit the packages for source/doc indexing in https://github.com/ros/rosdistro so that they undergo new package review.

The tutorial http://wiki.ros.org/rosdistro/Tutorials/Indexing%20Your%20ROS%20Repository%20for%20Documentation%20Generation will get you started with that. Once the PRs are open for each package, please link them here and once they are merged, I can complete this release team setup.

**Comment by mhubii** [comment]
thank you for sharing this resource, I'll be creating a PR there shortly and might maybe start with publishing a single package at first!

**Comment by mhubii** [comment]
closing this temporarily
